---
- name: Provision EC2 instance
  hosts: localhost
  vars:
      region:   eu-west-1
      ami:      ami-bff32ccc
      set_dns:  False
      instance: t2.nano
  connection: local
  gather_facts: false
  tasks:
    - name: Create a security group for cd
      local_action: 
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for webserver Servers
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launch instance
      ec2:
        keypair={{ keypair }}
        instance_type={{ instance }}
        image={{ ami }}
        region={{ region }}
        group={{ security_group }}
        wait=yes
      register: ec2
      
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_dns_name }}
                    groupname=launched
      with_items: ec2.instances

    - name: Ensure DNS entry exists
      route53: command=create overwrite=yes
               record=ci.{{ dns_zone }} type=A zone={{ dns_zone }}
               value={{ item.public_ip }}
      with_items: ec2.instances
      when: set_dns

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }}
                    port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
